
package pojoClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpDetailsPortService", targetNamespace = "https://www.howtodoinjava.com/xml/school", wsdlLocation = "http://localhost:7777/service/empDetailsWSDl.wsdl")
public class EmpDetailsPortService
    extends Service
{

    private final static URL EMPDETAILSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPDETAILSPORTSERVICE_EXCEPTION;
    private final static QName EMPDETAILSPORTSERVICE_QNAME = new QName("https://www.howtodoinjava.com/xml/school", "EmpDetailsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/service/empDetailsWSDl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPDETAILSPORTSERVICE_WSDL_LOCATION = url;
        EMPDETAILSPORTSERVICE_EXCEPTION = e;
    }

    public EmpDetailsPortService() {
        super(__getWsdlLocation(), EMPDETAILSPORTSERVICE_QNAME);
    }

    public EmpDetailsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPDETAILSPORTSERVICE_QNAME, features);
    }

    public EmpDetailsPortService(URL wsdlLocation) {
        super(wsdlLocation, EMPDETAILSPORTSERVICE_QNAME);
    }

    public EmpDetailsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPDETAILSPORTSERVICE_QNAME, features);
    }

    public EmpDetailsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpDetailsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpDetailsPort
     */
    @WebEndpoint(name = "EmpDetailsPortSoap11")
    public EmpDetailsPort getEmpDetailsPortSoap11() {
        return super.getPort(new QName("https://www.howtodoinjava.com/xml/school", "EmpDetailsPortSoap11"), EmpDetailsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpDetailsPort
     */
    @WebEndpoint(name = "EmpDetailsPortSoap11")
    public EmpDetailsPort getEmpDetailsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.howtodoinjava.com/xml/school", "EmpDetailsPortSoap11"), EmpDetailsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPDETAILSPORTSERVICE_EXCEPTION!= null) {
            throw EMPDETAILSPORTSERVICE_EXCEPTION;
        }
        return EMPDETAILSPORTSERVICE_WSDL_LOCATION;
    }

}
