
package pojoClasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpDetailsPort", targetNamespace = "https://www.howtodoinjava.com/xml/school")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpDetailsPort {


    /**
     * 
     * @param empDetailsRequest
     * @return
     *     returns pojoClasses.EmpDetailsResponse
     */
    @WebMethod(operationName = "EmpDetails")
    @WebResult(name = "EmpDetailsResponse", targetNamespace = "https://www.howtodoinjava.com/xml/school", partName = "EmpDetailsResponse")
    public EmpDetailsResponse empDetails(
            @WebParam(name = "EmpDetailsRequest", targetNamespace = "https://www.howtodoinjava.com/xml/school", partName = "EmpDetailsRequest")
                    EmpDetailsRequest empDetailsRequest);

}
